import { NextResponse } from 'next/server';
import { Pool } from 'pg';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL
});

function cleanHtmlOutput(text: string): string {
  if (!text) return "";
  let cleaned = text.trim();
  cleaned = cleaned.replace(/^```html\s*/i, '');
  cleaned = cleaned.replace(/^```\s*/, '');
  cleaned = cleaned.replace(/\s*```$/, '');
  return cleaned.trim();
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { productName, features, tone, email } = body;

    if (!email) {
      return NextResponse.json({ error: "EMAIL_REQUIRED" }, { status: 400 });
    }

    // 1. Fetch user to check credits
    let userRes = await pool.query("SELECT ai_credits FROM users WHERE email = $1", [email]);
    if (userRes.rows.length === 0) {
      await pool.query(`
        INSERT INTO users (id, email, full_name, role, ai_credits)
        VALUES ($1, $2, $3, $4, $5)
        ON CONFLICT (email) DO NOTHING
      `, ['admin_auto_' + Date.now(), email, 'Tagki Admin', 'admin', 1000]);
      
      userRes = await pool.query("SELECT ai_credits FROM users WHERE email = $1", [email]);
    }

    const currentCredits = userRes.rows[0].ai_credits !== null ? Number(userRes.rows[0].ai_credits) : 40;
    if (currentCredits <= 0) {
      return NextResponse.json({ error: "OUT_OF_CREDITS" }, { status: 403 });
    }

    // 2. Fetch AI configurations from database
    const configRes = await pool.query("SELECT value FROM settings WHERE key = $1", ['ai_copywriter_config']);
    let aiConfig = null;
    if (configRes.rows.length > 0) {
      const rawVal = configRes.rows[0].value;
      aiConfig = typeof rawVal === 'string' ? JSON.parse(rawVal) : rawVal;
    }

    if (!aiConfig) {
      // Fallback defaults
      aiConfig = {
        provider: process.env.GEMINI_API_KEY ? 'gemini' : 'openai',
        apiKey: process.env.OPENAI_API_KEY || process.env.GEMINI_API_KEY || '',
        model: process.env.GEMINI_API_KEY ? 'gemini-1.5-flash' : 'gpt-4o-mini',
        systemPrompt: "Bạn là chuyên gia Copywriter E-commerce. Hãy tạo bài mô tả sản phẩm bằng định dạng HTML chuẩn (chứa <h2>, <h3>, <p>, <ul>, <li>, emoji/icon sinh động) theo công thức AIDA (Attention, Interest, Desire, Action) và tối ưu từ khóa SEO. Đầu ra chỉ trả về mã HTML sạch để chèn trực tiếp vào Editor, không bao gồm codeblock markdown (```html)."
      };
    }

    const { provider, apiKey, model, systemPrompt } = aiConfig;

    if (!apiKey) {
      return NextResponse.json({ error: "API_KEY_MISSING" }, { status: 500 });
    }

    // Prepare user prompt
    const userPrompt = `Tên sản phẩm: ${productName}\nƯu điểm/Tính năng nổi bật: ${features}\nTông giọng: ${tone || 'Thuyết phục bán hàng'}`;

    let htmlContent = "";

    // 3. Call corresponding AI API
    if (provider === 'gemini') {
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model || 'gemini-1.5-flash'}:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [
                { text: `${systemPrompt}\n\nYêu cầu tạo bài viết cho:\n${userPrompt}` }
              ]
            }
          ],
          generationConfig: {
            temperature: 0.7
          }
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error?.message || "Gemini API error");
      }

      const data = await response.json();
      htmlContent = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
    } else {
      // OpenAI default
      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: model || 'gpt-4o-mini',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt }
          ],
          temperature: 0.7
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error?.message || "OpenAI API error");
      }

      const data = await response.json();
      htmlContent = data.choices?.[0]?.message?.content || "";
    }

    // Clean HTML Markdown block formatting if generated by the LLM
    htmlContent = cleanHtmlOutput(htmlContent);

    // 4. Deduct credit and update database
    const newCredits = currentCredits - 1;
    await pool.query("UPDATE users SET ai_credits = $1 WHERE email = $2", [newCredits, email]);

    return NextResponse.json({
      success: true,
      content: htmlContent,
      remainingCredits: newCredits
    });

  } catch (error: any) {
    console.error("AI Copywriter error:", error);
    return NextResponse.json({ error: "API_ERROR", message: error.message }, { status: 500 });
  }
}
